CREATE TABLE IF NOT EXISTS winners(
year INT,
subject TEXT,
winner TEXT,
country TEXT,
category TEXT);
INSERT INTO winners(year,subject,winner,country,category)VALUES
(1827,"PHYSICS","NOBLE PRIZE","SWEDEN","BOTANIST"),
(1987,"LITERATURE","NOBLE PRIZE","GERMANY","POET"),
(1789,"CHEMISTRY","NOBLE PRIZE","AUSTRIA","CHEMIST"),
(1897,"ZOOLOGY","NOBLE PRIZE","ENGLAND","ZOOLOGIST");

SELECT * FROM winners
WHERE SUBJECT NOT LIKE 'P%';